on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened, closed]
    branches:
      - main

jobs:
  build_and_deploy_job:
    if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.action != 'closed')
    runs-on: ubuntu-latest
    name: Build and Deploy Job
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
          lfs: false

      - name: Set up dependencies
        run: sudo apt-get update

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18" # Version de Node.js à utiliser

      - name: Install Dependencies
        run: npm install --omit=dev

      - name: Clean up node_modules
        run: |
          npm prune --production

      - name: Generate Prisma Client
        run: npx prisma generate # Génération du client Prisma

      - name: Cache node_modules
        uses: actions/cache@v3
        with:
          path: node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Build And Deploy
        id: builddeploy
        env:
          NEXTAUTH_URL: ${{ secrets.NEXTAUTH_URL }}
          AZURE_AD_CLIENT_ID: ${{ secrets.AZURE_AD_CLIENT_ID }}
          AZURE_AD_CLIENT_SECRET: ${{ secrets.AZURE_AD_CLIENT_SECRET }}
          AZURE_AD_TENANT_ID: ${{ secrets.AZURE_AD_TENANT_ID }}
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_LIVELY_BEACH_0CADDFF10 }}
          repo_token: ${{ secrets.GITHUB_TOKEN }} # Utilisé pour les intégrations GitHub (par ex. commentaires sur les PR)
          action: "upload"
          ###### Repository/Build Configurations - Ces valeurs peuvent être configurées selon vos besoins ######
          app_location: "/" # Chemin du code source de l'application
          api_location: "api" # Chemin du code source de l'API - ajustez le chemin selon vos besoins
          output_location: ".next" # Dossier de contenu de l'application générée
          ###### Fin des configurations du dépôt/de la build ######

  close_pull_request_job:
    if: github.event_name == 'pull_request' && github.event.action == 'closed'
    runs-on: ubuntu-latest
    name: Close Pull Request Job
    steps:
      - name: Close Pull Request
        id: closepullrequest
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_LIVELY_BEACH_0CADDFF10 }}
          action: "close"
